# Generated by Django 4.2.1 on 2023-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('taikhoan', models.CharField(max_length=10)),
                ('matkhau', models.CharField(max_length=10)),
                ('gmail', models.CharField(max_length=30)),
                ('thoiquen', models.CharField(max_length=50)),
                ('diachi', models.CharField(max_length=50)),
                ('thoigian', models.DateTimeField()),
            ],
        ),
    ]
